[workspace]
resolver = "3"
members = ["crates/playtime", "crates/lag-probe", "crates/seed", "crates/tile-codec", "tools/tile-benchmark"]
exclude = ["archive/mc", "archive/mc-backup"]

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.dependencies]
mimalloc = { version = "0.1.52", default-features = false }
serde_json = { version = "1.0.151", features = ["preserve_order"] }
tokio = { version = "1.53.1", default-features = false }

[workspace.lints.rust]
unused_must_use = "deny"

[workspace.lints.clippy]
correctness = { level = "deny", priority = -1 }
perf = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }

[profile.release]
opt-level = 3
codegen-units = 1
debug = false
incremental = false
strip = true
lto = true
panic = "unwind"
